package: can_msgs
messages:
  - name: Frame
    path: msg
    stamp: header.stamp
    mapping:
      - {ros2.path: header.frame_id, proton.signal: header_frame_id, type: string}
      - {ros2.path: id, proton.signal: id, type: uint32}
      - {ros2.path: is_rtr, proton.signal: is_rtr, type: bool}
      - {ros2.path: is_extended, proton.signal: is_extended, type: bool}
      - {ros2.path: is_error, proton.signal: is_error, type: bool}
      - {ros2.path: dlc, proton.signal: dlc, type: uint32}
      - {ros2.path: data, ros2.length: 8, proton.signal: data, type: bytes}
