[metadata]
name=proton_ros2_adaptor_generator
version = attr: proton_ros2_adaptor_generator.__version__
author = Tom Wallis
author_email = thomas.wallis@rockwellautomation.com
maintainer = Tom Wallis
maintainer_email = thomas.wallis@rockwellautomation.com
description = Proton ROS 2 message bridge package generator

[develop]
script_dir=$base/lib/proton_ros2_adaptor_generator

[install]
install_scripts=$base/lib/proton_ros2_adaptor_generator
