name: proton_ros2 CI

on:
  push:
  pull_request:

permissions:
  actions: read
  contents: read
  pull-requests: write

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    container:
      image: ubuntu:24.04

    steps:
      - name: Install dependencies
        run: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y \
            git \
            python3 \
            python3-venv \
            python3-pip

      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Mark safe repository
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: venv setup
        run: |
          python3 -m venv venv
          . venv/bin/activate
          pip install --upgrade pip
          pip install pre-commit

      - name: Run pre-commit
        run: |
          . venv/bin/activate
          pre-commit run --all-files

  build:
    name: Build proton_ros2 Source
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/clearpathrobotics/clearpath_docker:jazzy-ci-common-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ros-tooling/action-ros-ci@0.4.8
        id: action_ros_ci_step
        with:
          target-ros2-distro: jazzy
          package-name: |
            proton_ros2_interfaces
            proton_ros2_adaptor_generator
            proton_ros2
            proton_ros2_node
          vcs-repo-file-url: dependencies.repos

  build_head:
    name: Build proton_ros2 Source with Head Branch
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/clearpathrobotics/clearpath_docker:jazzy-ci-common-latest
    steps:
      - uses: actions/checkout@v7
      - name: "[Repositories Updater] Checkout action"
        uses: actions/checkout@v7
        with:
          repository: clearpathrobotics/repos-dep-update-action
          ref: 0.0.5
          path: repos-dep-update-action
      - name: "[Repositories Updater] Install dependencies"
        run: |
          apt-get update
          apt-get install -y jq git python3 python3-pip
          python3 -m pip install yq --break-system-packages
      - name: "[Repositories Updater] Extract branch name"
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
      - name: "[Repositories Updater] Run action"
        uses: ./repos-dep-update-action/
        with:
          branch: ${{ steps.extract_branch.outputs.branch }}
          input: dependencies.repos
          output: updated_dependencies.repos
      - name: "[Repositories Updater] Print updated dependencies"
        run: |
          cat updated_dependencies.repos
      - uses: ros-tooling/action-ros-ci@0.4.8
        id: action_ros_ci_step
        with:
          target-ros2-distro: jazzy
          package-name: |
            proton_ros2_interfaces
            proton_ros2_adaptor_generator
            proton_ros2
            proton_ros2_node
          vcs-repo-file-url: updated_dependencies.repos

  build_base:
    if: github.event_name == 'pull_request'
    name: Build proton_ros2 Source with Base Branch
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/clearpathrobotics/clearpath_docker:jazzy-ci-common-latest
    steps:
      - uses: actions/checkout@v7
      - name: "[Repositories Updater] Checkout action"
        uses: actions/checkout@v7
        with:
          repository: clearpathrobotics/repos-dep-update-action
          ref: 0.0.5
          path: repos-dep-update-action
      - name: "[Repositories Updater] Install dependencies"
        run: |
          apt-get update
          apt-get install -y jq git python3 python3-pip
          python3 -m pip install yq --break-system-packages
      - name: "[Repositories Updater] Run action"
        uses: ./repos-dep-update-action/
        with:
          branch: ${{ github.event.pull_request.base.ref }}
          input: dependencies.repos
          output: updated_dependencies.repos
      - name: "[Repositories Updater] Print updated dependencies"
        run: |
          cat updated_dependencies.repos
      - uses: ros-tooling/action-ros-ci@0.4.8
        id: action_ros_ci_step
        with:
          target-ros2-distro: jazzy
          package-name: |
            proton_ros2_interfaces
            proton_ros2_adaptor_generator
            proton_ros2
            proton_ros2_node
          vcs-repo-file-url: updated_dependencies.repos
